### ISSUE TITLE
Fixed download URL gone

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#19]
Please help users identifying the latest version.
```bash
release="$(wget -qO- https://api.github.com/repos/mdom/dategrep/releases|sed -n '0,/^.*"tag_name": "\([0-9.]\+\)".*$/s//\1/p')"
```
https://github.com/mdom/dategrep/blob/master/README.pod#installation

**Comment by szepeviktor** [comment]
```
Download the dategrep binary directly from GitHub (without package management)

    apt-get install -y libdate-manip-perl
    R="$(wget -qO- https://api.github.com/repos/mdom/dategrep/releases|sed -n '0,/^.*"tag_name": "\([0-9.]\+\)".*$/s//\1/p')"
    wget -O /usr/local/bin/dategrep https://github.com/mdom/dategrep/releases/download/${R}/dategrep-standalone-small
    chmod +x /usr/local/bin/dategrep
```

**Comment by mdom** [comment]
Sorry for not looking into this earlier. As github doesn't allow direct linking of release files, i had to change my build process  to generate those links with every release. Do you think this solves the issue or should i include your script in contrib?

**Comment by szepeviktor** [comment]
Yes, thank you.

Some repos *include* the release files in `/dist` subdirectory, those addresses are permanent.

**Comment by mdom** [comment]
You mean inside the git repository? I've done that at work in the past and i was never happy with that  as the repository got very big very fast; especially with a 10MB file. I would actually prefer to upload the files to one of my servers and link those if the current solution is not enough. What do you think?

**Comment by szepeviktor** [comment]
I think my script (which uses GitHub API) is simple enough.

There was a /downloads feature: https://github.com/blog/1302-goodbye-uploads
`https://github.com/mdom/dategrep/downloads`

**Comment by szepeviktor** [comment]
See https://github.com/mdom/dategrep/wiki/Install-or-update-to-the-latest-dategrep-%22small%22-release-on-Debian

**Comment by mdom** [comment]
Thanks, i just added your script to contrib. Do you want to just reference it from the wiki page? Might be easier to just support the script in the normal repository.

**Comment by szepeviktor** [comment]
I leave it up to you.

There seems to be a shebang problem in /contrib


All the best! 

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
