### ISSUE TITLE
Microseconds in Apache error log

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#21]
Cloud you help me to match `[Mon Jul 06 06:45:16.915695 2015]`?

`%a %b %d %T.?????? %Y`

**Comment by szepeviktor** [comment]
Is it `--format '%a %b %d %T[0-9.]* %Y'`?

**Comment by mdom** [comment]
--format '%a %b %d %T(\.[0-9]+)? %Y' seems to work here...
