### ISSUE TITLE
Invalid lines

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#24]
Could there be an option to skip invalid lines, lines without date?
Now I use `sed -e '1!b;/^(Nothing .*$/d'`

My boot.log
```
(Nothing has been logged yet.)
Thu Dec 17 00:04:36 2015: [....] Checking root file system...fsck from util-linux 2.25.2
```

**Comment by mdom** [comment]
There already is ... :)  Please try --skip-unparsable and see if that's working for you.

**Comment by szepeviktor** [comment]
@mdom Could you please include it in `--help`?

**Comment by mdom** [comment]
Can you check again with the new Makefile.PL? My dist.ini missed the entry to install the dategrep script.

**Comment by szepeviktor** [comment]
I've meant in the documentation:
https://github.com/mdom/dategrep/blob/012a31ae896a7a4b588648fec9970ec4e772d6f6/bin/dategrep

**Comment by szepeviktor** [comment]
Thank you. It's in the help.
