### ISSUE TITLE
standalone-big does not contain parent.pm

### ISSUE THREAD

**Issue by holmboe** [mdom/dategrep#26]
When trying to run dategrep-standalone-big I get this:

```
./dategrep
Can't locate parent.pm in @INC (@INC contains: FatPacked::8076224=HASH(0x7b3bc0) /usr/lib/perl5/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/5.10.0 /usr/lib/perl5/site_perl/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.10.0 /usr/lib/perl5/vendor_perl/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.10.0 /usr/lib/perl5/vendor_perl .) at ./dategrep line 13.
BEGIN failed--compilation aborted at ./dategrep line 13.
Compilation failed in require at ./dategrep line 9.
BEGIN failed--compilation aborted at ./dategrep line 9.
Compilation failed in require at ./dategrep line 4016.
BEGIN failed--compilation aborted at ./dategrep line 4016.
```

My understanding is that the standalone-big packaging should contain the dependencies?

This was observed on a SUSE Linux Enterprise Server 11 SP3 machine. The workaround is to install perl-parent from "devel languages perl" on download.opensuse.org. Do so with `zypper ar http://download.opensuse.org/repositories/devel:/languages:/perl/SLE_11_SP3/devel:languages:perl.repo` and then `zypper in perl-parent`.

**Comment by mdom** [comment]
It contains all dependencies that are not part of perl core. As SUSE seems to install only a minimal set of perl modules, parent.pm is missing. I'll add core modules to the standalone-big package for the next release. Thanks for reporting this problem!
