### ISSUE TITLE
0.55

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#27]
Hello!

Do you plan to solve some issues an release the next version?

**Comment by mdom** [comment]
I should probably do a new release first. Anything you want to see in the next release? Most of the issues are just some ideas i don't want to forget and not really issues with the current dategrep. Or do you disagree?

**Comment by szepeviktor** [comment]
OK-OK.
I'd like to be honest. logtail2 is the current choice in my alert script.
https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/syslog-errors.sh#L23
