### ISSUE TITLE
Implementing intervals

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#3]
Thank you!

**Comment by mdom** [comment]
Should be very easy to support, just let me sleep a few days over the best way to implement intervalls. --start and --end already parse intervalls from "now", so i just need a way to change dategreps "now".

**Comment by mdom** [comment]
Can you please check if the following is working for you in the newest commit:

dategrep --format rsyslog --multiline --from "1 hour ago from -17:00" --to "-17:00" /var/log/syslog

**Comment by szepeviktor** [comment]
Excuse me for being late.
It works!!

**Comment by szepeviktor** [comment]
`dategrep --format rsyslog --multiline --from "1 hour ago from -17:00" --to "-17:00" /var/log/syslog`

**Comment by szepeviktor** [comment]
Could you include it in the README for others?
