### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#30]
@mdom Please consider releasing those 35 commits.
https://github.com/mdom/dategrep/releases

**Comment by mdom** [comment]
I haven't released a new version because a new version of App::fatten broke my build script. I just tagged the current commit and released it. Can i ask why you need a release?

**Comment by szepeviktor** [comment]
> Can i ask why you need a release?

I have not particular problem.

**Comment by szepeviktor** [comment]
@mdom Hello!

My downloader - which picks the latest release - fails to operate.
https://github.com/szepeviktor/debian-server-tools/blob/master/package/dategrep-install.sh

Do you plan to add the compiled scripts to this release?

**Comment by szepeviktor** [comment]
@mdom Could you add those files please?

**Comment by mdom** [comment]
As i noted before, my build script can't currently create fatpackaged scripts as one of the dependencies broke. There are probably alternatives out there, but i don't have time to evaluate them. And I have the nagging feeling that I shouldn't have introduced non core dependencies at all. I won't reopen the issue as i don't have time in the foreseeable future to fix that, but i have it on the radar. The latest release of debian stable should contain all dependencies, so maybe that would be an alternative for you?

**Comment by szepeviktor** [comment]
Thank you for your work. I'll use v0.58 meanwhile.

> There are probably alternatives out there,
https://github.com/jhthorsen/app-implode
