### ISSUE TITLE
Add information to debian/changelog

### ISSUE THREAD

**Issue by mdom** [mdom/dategrep#33]
_Originally posted by @szepeviktor in https://github.com/mdom/dategrep/pull/32#issuecomment-443635608_

**Comment by mdom** [comment]
Good idea, i have to check how to automate this.

**Comment by mdom** [comment]
I've added the script update-debian-changelog in commit 1ff753d20a91c843096eba97962538b81d7abcb8. I also uploaded a prebuild debian package for stretch.

**Comment by szepeviktor** [comment]
Thank you.
