### ISSUE TITLE
Accurate to seconds

### ISSUE THREAD

**Issue by junly917** [mdom/dategrep#41]
With the latest version, filtering is limited to the minute level, not the exact second level

And it only filters up to the last minute. Down

~]$ echo $pre $cur 
11:58:12 12:02:30

~]$ ./dategrep/dategrep --format "%H:%M:%S" --start $pre --end $cur ./access.log.1 > grep.log

~]$ head -1 grep.log 
[2020-02-24 11:58:12,007]  ..........

~]$ ~]$ tail -1 grep.log    #12:01 and 12:02 and a lot more data
[2020-02-24 12:00:01,494]  ..........

**Comment by mdom** [comment]
I just added a test to see if dategrep works with seconds and at least on my machine it looks fine?! Could you run the test on your side? Would it be possible to share the relevant part of you access log? With which locale are you running the script?

Cheers, Mario

**Comment by mdom** [comment]
I'll close this issue, but do not hesitate to reopen it if you have any further information.
