### ISSUE TITLE
 Unparsable line

### ISSUE THREAD

**Issue by 3PO** [mdom/dategrep#5]
Hi,

i have lines like this in my syslog:

>Feb 07 20:24:33 [vdr] [4148] [plex]: 'ChannelSwitch'
>                - Last output repeated 3 times -
>Feb 07 20:24:35 [vdr] [5014] [plex]: Detected client discovery request from 192.168.177.10
>                - Last output repeated twice -
>Feb 07 20:24:43 [vdr] [4168] frontend 1/0 timed out while tuning to channel 0 (), tp 112539

But it seems, datagrep dont like this?

>vdr01_64 ~ # ./dategrep-standalone-big.pl --start "12:00" --end "12:15" --format "%b %d %H:%M:%S" /log/messages
>dategrep-standalone-big.pl: Unparsable line:                 - Last output repeated twice -
>vdr01_64 ~ #

**Comment by mdom** [comment]
You can try the switch --multiline, which does not insist to correctly parse every line by itself. If dategrep finds a line that does not match its time formats, the line is just added to the last line that matched.

**Comment by 3PO** [comment]
I dont know, what i do wrong, but it doesnt work:

>vdr01_64 ~ #  ./dategrep-standalone-big.pl  --multiline --start "12:00" --end "12:15" --format "%b %d %H:%M:%S" /log/messages
>dategrep-standalone-big.pl: No date found in first line: [parse] Invalid date string
>vdr01_64 ~ #

There are entries at at this time in my logfile:

>.....
>Feb 08 12:08:03 [vdr] epg2vdr: Processed channel 'S19.2E-1-1053-21104' - 'HSE24 HD' with 0 updates
>Feb 08 12:08:03 [vdr] epg2vdr: Processed channel 'S19.2E-133-33-40' - 'HSE24' with 3 updates
>Feb 08 12:08:03 [vdr] epg2vdr: Processed channel 'S19.2E-1-1007-4911' - 'ORF1 HD' with 1 updates
>Feb 08 12:08:03 [vdr] epg2vdr: Processed channel 'S19.2E-1-1117-13001' - 'ORF1' with 1 updates
>Feb 08 12:08:03 [vdr] epg2vdr: Processed channel 'S19.2E-133-17-19' - 'Junior' with 4 updates
>.....

**Comment by mdom** [comment]
Mhh, weird, works here for me with the same command line and input file. %b is the abbreviated month name according to the current locale. Do you maybe use a locale that does not abbreviate February to Feb? What's the ouput of locale(1)?

**Comment by 3PO** [comment]
vdr01_64 ~ # locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE=C
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
vdr01_64 ~ #

**Comment by mdom** [comment]
Ah, i got it. Dategrep checks if the first line of your file contains a date string, which can fail under multiline. I fixed that in the latest commit and you can already download the new prebuild scripts with the modifications. I still have to fix the corresponding code in sort_iterator() but as long as you don't use --sort-files or --interleave, it should now work.

**Comment by 3PO** [comment]
Thanks, no it works as expected. ;)
