### ISSUE TITLE
Debian rsyslog timestamp format

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#8]
Good morning!

How could it be that Debian's default `$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat` which looks like this `Jun__8_15:25:22` can be parsed with your "%b %d %H:%M:%S"?
I've replaces spaces with underscores.

**Comment by szepeviktor** [comment]
Yours has only one space before the day of the month.

**Comment by mdom** [comment]
Thanks for pointing that out, this is a documentation error. The code uses %e since commit 0716f70.

Cheers, Mario
